Feature/volume motion blur
tangent-opensource/cycles pull request #4
Opened 2021-02-10 17:05 UTC by sergeneren

#### Summary

Added support for eularian deformation motion blur for volumes. 

#### Change Log 

- Moved the MotionPosition enum from camera to a kernel_types.h to be able to use in kernel 
- Added a new function to *geom_volume.h* to support different up_axis configurations 
- Added velocity_scale field to ccl::Object and kernel object to scale volume motion blur 
- Added an fps field to Camera 

#### Testing 

Please see the hdCycles PR: [https://github.com/tangent-opensource/hdcycles/pull/75](https://github.com/tangent-opensource/hdcycles/pull/75)

2021-02-16 16:20 UTC, dedoardo commented
Hi @sergeneren,

The results look good and the implementation in line with the paper equations (6/7 in Eulerian Motion Blur). Just a couple of questions.

-  Is the behavior for out of bounds lookups specified by the extension type (extend/clip/etc)? The Arnold paper mentions dilatating the volume based on the (pre-filtered) max velocity. I wonder if the quality improvements justify it or not. Maybe this is already currently done during export in which case ignore the question. 
- Have you tried running it inside usdview?

2021-02-16 16:48 UTC, boberfly reviewed
Hey @sergeneren just a few things that popped out at me about the kernel code, feel free to correct me though as I am not sure on the gory details, I'm sure @skwerner has a better opinion here. :)

2021-02-16 16:48 UTC, boberfly commented on src/kernel/geom/geom_volume.h
> +  if(up_axis == 0){ /* Up axis Z*/
Feels a bit unfortunate that the axis needs checking in kernel code and introducing a branch. I guess there's no chance of defining the up axis in host code before device upload and embedding it into the transform or something along those lines? Maybe a stupid question from me, I am not sure. :)

2021-02-16 16:48 UTC, boberfly commented on src/kernel/kernel_types.h
> +  uint up_axis;
The padding on the end of this struct perhaps needs one removed now that an uint is introduced? Perhaps the checking could be done outside of kernel code though...

2021-02-24 10:38 UTC, skwerner requested changes

2021-02-24 10:38 UTC, skwerner commented on src/kernel/kernel_shader.h
> +             * https://www.arnoldrenderer.com/research/Arnold_TOG2018.pdf */
Thumbs up for leaving a pointer to the paper this is based on.

2021-02-24 10:38 UTC, skwerner commented on src/kernel/geom/geom_volume.h
> +  if(up_axis == 0){ /* Up axis Z*/
As discussed in the meeting, we should not be checking the up axis for now and assume that the renderer does not care about the up axis.

2021-02-24 16:27 UTC, sergeneren commented on src/kernel/geom/geom_volume.h
> +  if(up_axis == 0){ /* Up axis Z*/
up_axis is now removed from the kernel and render object. Cycles doesn't track the up_axis anymore.

2021-02-24 16:30 UTC, sergeneren reviewed
In the latest commit velocity transformation based on up_axis has been removed. I've tested the motion blur without conversion and only depending on the object transform and it is working correctly. 

We will assume that it is the dcc's responsibility to correctly transform the volumes based on their own axis configuration 

![volume_with_transform](https://user-images.githubusercontent.com/10246780/109032503-57c51e80-768b-11eb-810b-981c57083b0a.JPG)

2021-02-24 16:42 UTC, sergeneren commented
@dedoardo thanks for the review,

* Dilating the bounding box of the volume by the max filtered velocity has not been implemented here because based on my experience in Maya project I've seen that filtering had a significant impact on the time to first pixel (mainly because my filtering implementation was single-threaded and did lots of sorting). But during the production, out of many shots there was only two cases that needed dilation in the vel field and it was easily solved by expanding the velocity vdb by some voxel amount before export and filtering was only needed once. So it was a deliberate choice.
* I couldn't yet test it in usdview (having a rez package conflict about usd version and I'm trying to resolve it)

2021-02-24 19:13 UTC, dedoardo commented
Thanks for the reply @sergeneren 
- Good to know, if it's happening so rarely I agree it's probably best to resolve the issue during export when needed rather than slow down all the other volumes. I'm guessing it was something with very high velocity causing this?
- Ok, I asked exactly because I was running into similar issues and wasn't sure whether it war related to this PR. It's more likely due to building issues.

2021-03-09 15:47 UTC, merged